### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by albert-ying** [mps9506/quarto-cv#9]
Hi I'm wondering how can I use Chinese in this template?

Usually adding `\usepackage{ctex}` works for latex, but in this case I got an error:

```
compilation failed- error
LuaTeX-ja error: File `jfm-zh_CN.lua' not found.
<recently read> ltj@@jfont@inner 
                 
l.1226 \tl_set:Nn \CJK@family { song } \selectfont
                                                
```

**Comment by mps9506** [comment]
I'll update the template to fix this.

**Comment by mps9506** [comment]
@albert-ying We can use quarto's built-in support for the `xeCJK` package now by setting the `CJKmainfont:` yaml key to a locally installed Asian script font. The xelatex pdf engine also has to be used:

```
---
title: CV
format:
  quarto-cv-pdf:
    pdf-engine: xelatex
author: William Gosset
date: last-modified
phone: 123-456-7890
address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
email: guinness@consumer-care.net
fontsize: 11pt
CJKmainfont: Noto Sans CJK JP
fontawesome: yes
---

# Heading 1

本ラげぎは瀬所な祭頂カレイエ聞記政義幸はゅくた裕態けざやゆ済51込ゆやン難都ぎゆきの制交ゃばをさ速会ゆ細効エ究導どね様親破そた。相ハテ挙要2芸ひそぜず援裁ぜだっみ洗際像マ教判くぽ表長ワタ取経シナ写皇マワ割96並掛焼詐加ぱげ。惑ラヘ位容らぼ馬学売エ北後フヲ部書つラルび井女相ラ局純主ぱ応終フセ告味てるー稿更ンらよ収94成ロヒ疑憲ぶ車取ヘハ山銘リ員知ド。

抜ゃね月情よ激案ひラし合暮ヱマ厳要1主ら返総画せいれ惑棋どレごイ磯北っよ枠細ミヘ多敢渓窮胡ゅと。身目ー靖堀報トヤホ養四シレ総8発ケサロキ強7討わちりの作発群ヲ断14朝隠シ谷帯ンぞ出村ハナ掲屋だむづじ世確組ロワ沢人ネヨコ駅昇捜昭垣だうぽ。字コモ表家2第み海停ロホ在苦ハチ渉断ね英再フめべ康知クモテ葛選スセ折内にラへ写再み大左め市皇トぽラお入社側圧ろぼつ。
```

![image](https://github.com/mps9506/quarto-cv/assets/11282246/c2fdcc6e-c614-43f1-bcd2-4cc5da7b13db)


I don't have any experience using Chinese characters so let me know if there are any problems.
